### ISSUE TITLE
Video stream not working(or display blank screen) on browser tab change

### ISSUE THREAD

**Issue by anuj255** [aullman/opentok-camera-filters#12]
Hi,

When I change my browser tab my video stream not working and showing blank screen to other publisher on the session and when I come back on same tab it works fine.

**Comment by aullman** [comment]
Yes, this is expected behaviour right now because the code is using `requestAnimationFrame` to draw the frames of the video. `requestAnimationFrame` does not run when the tab is in the background. You could possibly look into using setTimeout instead of requestAnimationFrame [here](https://github.com/aullman/opentok-camera-filters/blob/master/src/filterTask.js#L24). But I don't think it will perform very well.
